### ISSUE TITLE
Network Diagram Clarification

### ISSUE THREAD

**Issue by kunmukh** [so87/Home-Lab#1]
Hey Simon, could you provide some clarification in your network diagram. 
1>The "hypervisor 1.69" in your diagram is your server correct? 
2>Is the "Virtual Services" is like a VM(VMWare) running client machine? 
3>Is "Virtual Pen Testing VLAN" is also a separate VM?
4> "VPN Clients" are they services or machines? So, you have a VPN server running in the hypervisor, that the other VPN clients are connecting to? I am confused because would not your arrow connect to hypervisor 1.69, rather than the "Unifi Switch"?

**Comment by so87** [comment]
1. yes
2. yes
3. a vlan is a way of logically separating two networks even though in hardware they are using the same cords. software defined, and makes the network more secure because you are separating traffic of malicious services from known good traffic.
4. you can host a VPN server in the Unifi gateway, or you can do it in a VM, and you can even do it in a docker container. people external from the network will be placed on their own vlan. I drew arrows of this to see how traffic gets passed through my network.

**Comment by kunmukh** [comment]
Thank you.
